* General doom kbds
M-H/L/K/J      org-shiftmeta[fn:footnote example][direction]
m-h/l/k/j      org-meta[direction]

folding (unsorted):
z a      +org/toggle-fold
z o/c      +org/open-fold / +org/close-fold
z R/M      +org/open-all-folds / +org/close-all-folds
z O/C      outline-show-subtree / outline-hide-subtree
z r/m      +org/show-next-fold-level / +org/hide-next-fold-level

SPC m ,  org-switchb -- Switch between Org buffers.
With C-u prefix, restrict available buffers to files.
With C-u C-u prefix, restrict available buffers to agenda files.

~SPC m /~ / ~SPC m g G~ - counsel-org-goto-all

*Shift + arrows - change heading todo status!*

** used not frequently
SPC m I  org-toggle-inline-images
<C-M-S-left>    org-decrease-number-at-point<S-return>      org-table-copy-down
<C-M-S-right>   org-increase-number-at-point<S-right>       org-shiftright

** unknown/unclear purpose :tags_command:
SPC m o  org-set-property

SPC n m  org-tags-view
SPC m q  org-set-tags-command
SPC n Y  +org/export-to-clipboard-as-rich-text
SPC n y  +org/export-to-clipboard
SPC m e  org-export-dispatch
SPC m #  org-update-statistics-cookies
SPC m '  org-edit-special
SPC m c E       org-set-effort
C-c C-x E       org-inc-effort
C-M-t    org-transpose-element
SPC m g i       org-id-goto

Minor Mode Bindings: ----------

C-c " a  orgtbl-ascii-plot
C-c " g  org-plot/gnuplot
C-c C-x C-a     org-archive-subtree-default
C-c C-x C-c     org-columns
C-c C-x C-f     org-emphasize
C-c C-x A       org-archive-to-archive-sibling
C-c C-x C-l     org-latex-preview
C-c C-x G       org-feed-goto-inbox
C-c C-x I       org-info-find-node
C-c C-x P       org-set-property-and-value
C-c C-x [       org-reftex-citation
C-c C-x \       org-toggle-pretty-entities
C-c C-x C-r     org-toggle-radio-button
C-c C-x C-s     org-archive-subtree
C-c C-x a       org-toggle-archive-tag
C-c C-x C-t     org-toggle-time-stamp-overlays
C-c C-x b       org-tree-to-indirect-buffer
C-c C-x C-u     org-dblock-update
C-c C-x c       org-clone-subtree-with-time-shift
C-c C-x d       org-insert-drawer
C-c C-x C-w     org-cut-special
C-c C-x C-y     org-paste-special
C-c C-x g       org-feed-update-all
C-c C-x o       org-toggle-ordered-property
C-c C-x p       org-set-property
C-c C-x !       org-reload
C-c C-x q       org-toggle-tags-groups
C-c C-x v       org-copy-visible
C-c C-x x       org-dynamic-block-insert-dblock

* Navigation / editing
<insert-state> C-d       org-metaleft
<insert-state> C-t       org-metaright

** navigation
[ c      org-babel-previous-src-block
[ l      org-previous-link
[ h      org-backward-heading-same-level
] c      org-babel-next-src-block
] l      org-next-link
] h      org-forward-heading-same-level
g H      evil-org-top
g h      org-up-element
g s h    +org/goto-visible
SPC m g v       +org/goto-visible

<motion-state> g H       evil-org-top
<motion-state> g k       org-backward-element
<motion-state> g h       org-up-element
<motion-state> g l       org-down-element
<motion-state> g j       org-forward-element
<motion-state> g s       Prefix Command
<motion-state> g s h     +org/goto-visible

** editing
g Q      org-fill-paragraph
z n      org-tree-to-indirect-buffer
<operator-state> i E     evil-org-inner-element
<operator-state> i e     evil-org-inner-object
<operator-state> i R     evil-org-inner-subtree
<operator-state> i r     evil-org-inner-greater-element
<operator-state> a E     evil-org-an-element
<operator-state> a e     evil-org-an-object
<operator-state> a R     evil-org-a-subtree
<operator-state> a r     evil-org-a-greater-element

* Heading
SPC m *  org-ctrl-c-star -- make heading
~SPC m .~ / ~SPC m g g~  counsel-org-goto counsel-org-goto
SPC m h  org-toggle-heading
C-M-RET  org-insert-subheading

C-M-return  org-insert-subheading

** Subheading
> [source](http://pragmaticemacs.com/org-mode-tutorials/)
press `tab` on heading - **collapse heading**

`shift + tab` - collapse / uncollapse everything

* Text formatting

*bold* /italic/ +strikethrough+ =literal text= _underlined_ ~code~

> ~code~ generally appears the same as literal text

** Formatted blocks of text
*Text in these blocks can be edited via ~C-c '~
#+BEGIN_EXAMPLE
  <e tab

  This is an example block into which you can type text that you don't
  want org to mess with like a [[link]]
#+END_EXAMPLE

#+BEGIN_QUOTE
~<q tab~ -- This block encloses text that you want to appear as a quotation
#+END_QUOTE

#+BEGIN_CENTER
~<c tab~ -- This text will be centred when it is exported
#+END_CENTER

** Source code blocks
After 'python' keyword on line below you can write the output of the
code to a var and use it in next code-block
#+NAME: pythonic-numbers
#+BEGIN_SRC python :results list
  import random
  return [random.randrange(1, 20)
          for i in range( random.randrange(1, 20))]
#+END_SRC
after u execute this (~C-c C-c~) the output will appear below and
'pythonic-numbers' will contain value

#+BEGIN_SRC emacs-lisp :var numbers=pythonic-numbers
  (length numbers)
#+END_SRC

** Executing source code blocks
Org-mode can execute your source code blocks and add the output to
your file. This part of org-mode is called babel

#+BEGIN_SRC sh
  echo "Hello $USER! Today is `date`"
  exit
#+END_SRC

> text below is executed via ~C-c C-c~, while cursor on block above

#+RESULTS:
: Hello sad! Today is Пт авг 16 15:00:47 MSK 2019

* Lists
SPC m i  org-toggle-item
SPC m +  org-ctrl-c-minus -- Insert separator line in table or modify bullet status of line.
** bullet list
- bullet lists can be created like this (start a line with one or more space and a -
- pressing M-RET gives you a new bullet
- nested bullets:
  - like this one (I pressed M-RET TAB to indent it)
- shift + tab to unindent it
- reorder list items with M-up or M-down just like with section headings
- you can change bullet style using S-left and S-right

** checklists [0/4]
- [ ] we can even have check lists
- [ ] M-S-RET gives a new item with a check box
- [ ] C-c C-c check/uncheck a box
  - [ ] sub item
- [ ] track the number of items by adding '/' to the end of a line above a checklist - this updates when you check items off

** definition lists
- definition lists :: these are useful sometime
- item 2 :: M-RET again gives another item

* Tables

SPC m b -       org-table-insert-hline
SPC m b f       org-table-edit-formulas
SPC m b R       org-table-recalculate-buffer-tables
SPC m b h       org-table-field-info
SPC m b a       org-table-align
SPC m b b       org-table-blank-field
SPC m b r       org-table-recalculate
SPC m b c       org-table-create-or-convert-from-region
SPC m b s       org-table-sort-lines
SPC m b e       org-table-edit-field

SPC m b t f     org-table-toggle-formula-debugger
SPC m b t o     org-table-toggle-coordinate-overlays
SPC m b i H     org-table-hline-and-move
SPC m b i h     org-table-insert-hline
SPC m b i c     org-table-insert-column
SPC m b i r     org-table-insert-row
SPC m b d c     org-table-delete-column
SPC m b d r     org-table-kill-row

1) when you get to the "s" of comments, press TAB to go to the next line
2) go up to the previous line and use C-c - to add the row of dashes
3) next enter a few lines of data, using TAB to go through the cells
4) move rows and columns around using M-arrow and insert or delete rows and columns using M-S-arrow

| ID | x | y | comments     |
|----+---+---+--------------|
| a  | 1 | 2 | some         |
| b  | 3 | 4 | some comment |

`C-c |` - create an empty table / convert selected text to a table

ID  x   y
A   2   4
B   3   9

`M-x org-table-export` -- save tables to their own files (while cursor in the table)

> For the format, type orgtbl-to and press TAB to see the available
options (e.g. orgtbl-to-csv will convert to csv in the output file)

** Formulae
use formulae to do arithmetic on tables, and use them like a spreadsheet.

more [[http://orgmode.org/worg/org-tutorials/org-spreadsheet-intro.html][info]]

* Links and images

SPC m l L   org-insert-all-links
SPC m l i   org-id-store-link
SPC m l S   org-insert-last-stored-link
SPC m l l   org-insert-link
SPC m l c   org-cliplink
SPC m l s   org-store-link
SPC m l d   +org/remove-link
SPC m l t   org-toggle-link-display
SPC m a l       +org/attach-file-and-insert-link

Open links with ~C-c C-o~ shortcut

[[http://pragmaticemacs.com/emacs/org-mode-basics-iii-add-links-and-images-to-you-notes/][how to paste local img/gifs into document]]

z i      org-toggle-inline-images

~spc n l~ (org-store-link) - store link (to be able to choose it later from the ~spc m l l~ popup menu)

structure of link in org mode:

#+BEGIN_EXAMPLE
  [[link_address][description]]
#+END_EXAMPLE

`C-c C-o` - open link below cursor

** internal links
Links to custom IDs will point to the corresponding headline. The preferred match for a text link is a
dedicated target: the same string in double angular brackets, like ‘<<My Target>>’.

[[Links and images][in file link]] - address part matches a headline in this doc.
[[my target]] - link to 'my target above'

If no dedicated target exists, the link will then try to match the exact name of an element within the
buffer. Naming is done with the #+NAME keyword:

#+NAME: some name
content here

[[some name]] - link to content with #id

** link to a file
(in doom) press ~spc m l l~, type /file:/ and choose needed file.

To add particular headline to the link add /::{headline}/ in the end of a link.
You also can specify line number instead of headline.

[[file:emacs_tut.md::Basics][link to 'Basics' in file 'emacs_tut' in this repo]]

** elisp link
There r many org types links to create, full list can be found on official org documentation. In this link u
type /elisp:/ and then any elisp code or available emacs command.

[[elisp:org-agenda][My org agenda]]

* Exporting .org file
~C-c C-e~ -- export file, then choose needed options

Examples:
~C-c C-e h o~ -- export to HTML and open it
~C-c C-e l o~ -- export to latex adn compile it to produce a pdf and open it

Also check how to tweak the look of exported file [[http://pragmaticemacs.com/emacs/org-mode-basics-v-exporting-your-notes/][here]]

* Timer
C-c C-x .       org-timer
C-c C-x 0       org-timer-start
C-c C-x ,       org-timer-pause-or-continue
C-c C-x ;       org-timer-set-timer
C-c C-x -       org-timer-item
C-c C-x _       org-timer-stop

* Clock
SPC m c i       org-clock-in
SPC m c -       org-clock-timestamps-down
SPC m c e       org-clock-modify-effort-estimate
SPC m c =       org-clock-timestamps-up
SPC m c g       org-clock-goto
SPC m c l       +org/toggle-last-clock
SPC m g c       org-clock-goto
SPC m c I       org-clock-in-last
SPC m c R       org-clock-report
SPC m c r       org-resolve-clocks
SPC m c c       org-clock-cancel
SPC m c t       org-evaluate-time-range
SPC m c d       org-clock-mark-default-task
SPC m c o       org-clock-out
SPC n C  org-clock-cancel
SPC n o  org-clock-goto
SPC n c  +org/toggle-last-clock
C-c C-x C-d     org-clock-display
C-c C-x TAB     org-clock-in

* Ultimate agenda guide
SPC o a a       org-agenda               SPC o a t       org-todo-list
SPC o a m       org-tags-view            SPC o a v       org-search-view

<M-S-return>    org-insert-todo-heading

SPC m d T       org-time-stamp-inactive
SPC m d s       org-schedule
SPC m d d       org-deadline
SPC m d t       org-time-stamp

~SPC X/nn~ / ~SPC p O~ - org-capture / counsel-projectile-org-capture
SPC o A / SPC n a - org-agenda
SPC n F - +default/browse-notes -- see all files with your notes including agendas and todos
SPC m T  org-todo-list
SPC m t  org-todo *important*
SPC n S - +default/org-notes-headlines -- Jump to an Org headline in org-agenda-files.
SPC n s - +default/org-notes-search -- Perform a text search on org-directory.
SPC n t  org-todo-list
SPC n v  org-search-view -- better C-h f this thing, huge utility

C-S-h/l/k/j - org-shift[direction]
SPC m A  org-archive-subtree -- C-h f *important*

SPC m x  org-toggle-checkbox

SPC m g x       org-capture-goto-last-stored

SPC m s p d     org-priority-down        SPC m s p u     org-priority-up
SPC m s p p     org-priority

C-#      org-table-rotate-recalc-marks
C-'      org-cycle-agenda-files

C-c C-x <       org-agenda-set-restriction-lock
C-c C-x >       org-agenda-remove-restriction-lock

** haven't yet used kbds
SPC n N - org-capture-goto-target -- Go to the target location of a capture template.

** Adding TODO's
Added some settings for org TODO in my config

- ~, oc~ :: add todo item (do it from anywhere)
- ~C-c C-s~ :: add scheduled date to an item (while adding todo)
- ~C-c C-d~ :: add deadline (while adding todo)

=Items above will pop up a calendar, navigate there=

near heading which'll pop up name the todo item and below any description (optional)

~C-c C-c~ - save todo item

default priority is A, ~Shift + arrows~ - change it

** Viewing agenda
~, oa t~ - view todo tasks
~, oa n~ - display list of scheduled tasks and unscheduled tasks below it

- $ :: cross an item off your list. which marks it as done
     and archives the item in a file called todo.org_archive
- ~Shift + up/down~ :: change priority or an item
- ~E~ :: view notes to go with item
- ~RET~ :: edit or view an item
- ~q~ :: quit todo buffer (after opening with ~, oa~)

Edited ~org-capture-templates~ so all new tasks will be today's date by default.

~Shift + arrows~ - edit date

** Additional not sorted kbds
C-c C-d  org-deadline
C-c ,    org-priority
C-c C-e  org-export-dispatch
C-c -    org-ctrl-c-minus
C-c C-f  org-forward-heading-same-level
C-c .    org-time-stamp
C-c /    org-sparse-tree
C-c C-j  org-goto
C-c :    org-toggle-fixed-width
C-c C-k  org-kill-note-or-show-branches
C-c ;    org-toggle-comment
C-c C-l  org-insert-link
C-c <    org-date-from-calendar
C-c RET  org-ctrl-c-ret
C-c =    org-table-eval-formula
C-c C-o  org-open-at-point
C-c >    org-goto-calendar
C-c C-q  org-set-tags-command
C-c ?    org-table-field-info
C-c C-r  org-reveal
C-c @    org-mark-subtree
C-c C-s  org-schedule
C-c [    org-agenda-file-to-front
C-c C-t  org-todo
C-c \    org-match-sparse-tree
C-c ]    org-remove-file
C-c ^    org-sort
C-c `    org-table-edit-field
C-c C-y  org-evaluate-time-range
C-c {    org-table-toggle-formula-debugger
C-c C-z  org-add-note
C-c |    org-table-create-or-convert-from-region
C-c }    org-table-toggle-coordinate-overlays
C-c C-^  org-up-element
C-c ~    org-table-create-with-table.el
C-c C-_  org-down-element
C-c C-S-l       +org/remove-link
C-c SPC  org-table-blank-field
C-c C-*  org-list-make-subtree
C-c C-,  org-insert-structure-template
C-c #    org-update-statistics-cookies
C-c <C-tab>     org-force-cycle-archived
C-c %    org-mark-ring-push

* Refiling | [[https://orgmode.org/manual/Refile-and-Copy.html][docs]]
When reviewing the captured data, you may want to refile or to copy some of the entries into a different list,
for example into a project. Cutting, finding the right location, and then pasting the note is cumbersome. To
simplify this process, you can use the following special command.

C-c C-w  org-refile
C-c M-w  org-refile-copy
SPC m g r       org-refile-goto-last-stored

* attachments
SPC m a D       org-attach-delete-all
SPC m a O       org-attach-open-in-emacs
SPC m a n       org-attach-new
SPC m a R       org-attach-reveal-in-emacs
SPC m a o       org-attach-open
SPC m a S       org-attach-sync
SPC m a r       org-attach-reveal
SPC m a a       org-attach
SPC m a s       org-attach-set-directory
SPC m a d       org-attach-delete-one
SPC m a u       org-attach-url
SPC m a f       +org/find-file-in-attachments

* Org publishing
[[https://orgmode.org/manual/Publishing.html#Publishing][docs]]

SPC m P P       org-publish-current-project
SPC m P p       org-publish
SPC m P a       org-publish-all
SPC m P s       org-publish-sitemap
SPC m P f       org-publish-current-file

* babel kbds (unsorted)
C-x n b  org-narrow-to-block
C-x n s  org-narrow-to-subtree
C-x n e  org-narrow-to-element
C-c C-v C-a     org-babel-sha1-hash
C-c C-v b       org-babel-execute-buffer
C-c C-v C-b     org-babel-execute-buffer
C-c C-v c       org-babel-check-src-block
C-c C-v C-c     org-babel-check-src-block
C-c C-v d       org-babel-demarcate-block
C-c C-v C-d     org-babel-demarcate-block
C-c C-v e       org-babel-execute-maybe
C-c C-v C-e     org-babel-execute-maybe
C-c C-v f       org-babel-tangle-file
C-c C-v C-f     org-babel-tangle-file
C-c C-v g       org-babel-goto-named-src-block
C-c C-v TAB     org-babel-view-src-block-info
C-c C-v h       org-babel-describe-bindings
C-c C-v C-j     org-babel-insert-header-arg
C-c C-v i       org-babel-lob-ingest
C-c C-v C-l     org-babel-load-in-session
C-c C-v j       org-babel-insert-header-arg
C-c C-v C-n     org-babel-next-src-block
C-c C-v k       org-babel-remove-result-one-or-many
C-c C-v C-o     org-babel-open-src-block-result
C-c C-v l       org-babel-load-in-session
C-c C-v C-p     org-babel-previous-src-block
C-c C-v n       org-babel-next-src-block
C-c C-v C-r     org-babel-goto-named-result
C-c C-v o       org-babel-open-src-block-result
C-c C-v C-s     org-babel-execute-subtree
C-c C-v p       org-babel-previous-src-block
C-c C-v C-t     org-babel-tangle
C-c C-v r       org-babel-goto-named-result
C-c C-v C-u     org-babel-goto-src-block-head
C-c C-v s       org-babel-execute-subtree
C-c C-v C-v     org-babel-expand-src-block
C-c C-v t       org-babel-tangle
C-c C-v C-x     org-babel-do-key-sequence-in-edit-buffer
C-c C-v u       org-babel-goto-src-block-head
C-c C-v C-z     org-babel-switch-to-session
C-c C-v v       org-babel-expand-src-block
C-c C-v x       org-babel-do-key-sequence-in-edit-buffer
C-c C-v I       org-babel-view-src-block-info
C-c C-v z       org-babel-switch-to-session-with-code
C-c C-v a       org-babel-sha1-hash

* Footnotes
SPC m f  org-footnote-new -- insert a footnote in current document
C-c C-x f       org-footnote-action

[fn:footnote example]
